# Generated by Django 3.1.7 on 2021-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('antiragging_students', models.FileField(default=None, upload_to='antiragging/students')),
                ('antiragging_parents', models.FileField(default=None, upload_to='antiragging/parents')),
                ('code_conduct', models.FileField(default=None, upload_to='code_conduct')),
                ('undertaking_hostel', models.FileField(default=None, upload_to='undertaking_hostel')),
            ],
        ),
    ]
