# Generated by Django 3.1 on 2022-03-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20210304_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='antiragging_parents',
        ),
    ]
